fixed cs-fixer script, try to find php-cs-fixer in both bin/ and vendor/bin dirs

diff --git a/src/cs-fixer b/src/cs-fixer
--- a/src/cs-fixer
+++ b/src/cs-fixer
@@ -1,7 +1,15 @@
 #!/bin/bash
 
-CMD=vendor/bin/php-cs-fixer
 CONFIG=vendor/rabbitinternet/cs-fixer/src/.php_cs
+PATHS=("bin/php-cs-fixer" "vendor/bin/php-cs-fixer");
+
+echo "[GIT COMMIT HOOK] Run PHP-FIXER"
+
+for i in ${PATHS[@]}; do
+    [ -f $i ] && CMD=$i
+done
+
+[ -z $CMD ] && echo "Error: php-cs-fixer not found in " && for i in ${PATHS[@]}; do echo "$i"; done && exit 1
 
 function show_help() {
     echo -e "\n Usage: cs-fixer <command> \n\n Available commands: \n
